// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package case2

// Injectors from wire_inject.go:

func InitializeUserService(foo string, bar int) *UserService {
	case2MockUserRepo := NewMockUserRepo(foo, bar)
	userService := NewUserService(case2MockUserRepo)
	return userService
}
